[package]
name = "dispatching"
version = "0.0.0"


[addresses]
dispatching = "_"

#[dev-addresses]
#dispatching = "0xd119"

[dependencies]
AccudoFramework = { local = "../../framework/accudo-framework" }
