version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "accudo-labs/security"
      - "accudo-labs/prod-eng"
    labels:
      - "CICD:run-e2e-tests"
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 0
