[package]
name = "accudo-api-test-context"
description = "Accudo API test context"
version = "0.2.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-api = { workspace = true }
accudo-api-types = { workspace = true }
accudo-cached-packages = { workspace = true }
accudo-config = { workspace = true }
accudo-crypto = { workspace = true }
accudo-db = { workspace = true, features = ["fuzzing"] }
accudo-executor = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-framework = { workspace = true }
accudo-genesis = { workspace = true }
accudo-indexer-grpc-table-info = { workspace = true }
accudo-mempool = { workspace = true, features = ["fuzzing"] }
accudo-mempool-notifications = { workspace = true }
accudo-sdk = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-temppath = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true }
accudo-vm-logging = { workspace = true }
accudo-vm-validator = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
goldenfile = { workspace = true }
hyper = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
warp = { workspace = true }
warp-reverse-proxy = { workspace = true }
