[package]
name = "accudo-peer-monitoring-service-server"
description = "The peer monitoring service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-bounded-executor = { workspace = true }
accudo-build-info = { workspace = true }
accudo-channels = { workspace = true }
accudo-config = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-netcore = { workspace = true }
accudo-network = { workspace = true }
accudo-peer-monitoring-service-types = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-time-service = { workspace = true }
accudo-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
accudo-crypto = { workspace = true }
accudo-network = { workspace = true, features = ["fuzzing"] }
accudo-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
