[package]
name = "accudo-indexer"
description = "Accudo Indexer"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-api = { workspace = true }
accudo-api-types = { workspace = true }
accudo-bitvec = { workspace = true }
accudo-config = { workspace = true }
accudo-logger = { workspace = true }
accudo-mempool = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-runtimes = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bigdecimal = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true, features = [
    "chrono",
    "postgres",
    "r2d2",
    "numeric",
    "serde_json",
] }
diesel_migrations = { workspace = true }
field_count = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
accudo-api-test-context = { workspace = true }
