[package]
name = "accudo-api-tester"
description = "Accudo developer API tester"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-api-types = { workspace = true }
accudo-cached-packages = { workspace = true }
accudo-framework = { workspace = true }
accudo-logger = { workspace = true }
accudo-push-metrics = { workspace = true }
accudo-rest-client = { workspace = true }
accudo-sdk = { workspace = true }
accudo-types = { workspace = true }
futures = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
