[package]
name = "generate-format"
description = "Accudo core type checker to ensure compatibility"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-api-types = { workspace = true }
accudo-config = { workspace = true }
accudo-consensus = { workspace = true, features = ["fuzzing"] }
accudo-consensus-types = { workspace = true }
accudo-crypto = { workspace = true }
accudo-crypto-derive = { workspace = true }
accudo-network = { workspace = true }
accudo-types = { workspace = true, features = ["fuzzing"] }
bcs = { workspace = true }
clap = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }
serde = { workspace = true }
serde-reflection = { workspace = true }
serde_yaml = { workspace = true }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
