[package]
name = "accudo-storage-interface"
description = "Accudo storage interface"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-crypto = { workspace = true }
accudo-experimental-layered-map = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-scratchpad = { workspace = true }
accudo-secure-net = { workspace = true }
accudo-types = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
dashmap = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
accudo-types = { workspace = true, features = ["fuzzing"] }
bytes = { workspace = true }
lru = { workspace = true }

[features]
default = []
fuzzing = ["accudo-types/fuzzing"]

[package.metadata.cargo-machete]
ignored = ["proptest"]
