[package]
name = "accudo-db"
description = "Accudo database"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-accumulator = { workspace = true }
accudo-config = { workspace = true }
accudo-crypto = { workspace = true }
accudo-db-indexer = { workspace = true }
accudo-db-indexer-schemas = { workspace = true, features = ["fuzzing"] }
accudo-executor-types = { workspace = true }
accudo-experimental-runtimes = { workspace = true }
accudo-infallible = { workspace = true }
accudo-jellyfish-merkle = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-proptest-helpers = { workspace = true, optional = true }
accudo-resource-viewer = { workspace = true }
accudo-rocksdb-options = { workspace = true }
accudo-schemadb = { workspace = true }
accudo-scratchpad = { workspace = true }
accudo-storage-interface = { workspace = true, features = ["fuzzing"] }
accudo-temppath = { workspace = true, optional = true }
accudo-types = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
dashmap = { workspace = true }
either = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true, optional = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
accudo-block-executor = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
accudo-proptest-helpers = { workspace = true }
accudo-schemadb = { workspace = true, features = ["fuzzing"] }
accudo-scratchpad = { workspace = true, features = ["fuzzing"] }
accudo-temppath = { workspace = true }
accudo-types = { workspace = true }
ouroboros = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "accudo-proptest-helpers", "accudo-temppath", "accudo-crypto/fuzzing", "accudo-jellyfish-merkle/fuzzing", "accudo-types/fuzzing", "accudo-executor-types/fuzzing", "accudo-schemadb/fuzzing", "accudo-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["accudo-temppath", "clap", "crossbeam-channel", "owo-colors", "indicatif"]
