[package]
name = "stablecoin"
version = "0.0.0"


[addresses]
stablecoin = "_"
master_minter = "_"
minter = "_"
pauser = "_"
denylister = "_"

[dev-addresses]
stablecoin = "0xcafe"
master_minter = "0xbab"
minter = "0xface"
pauser = "0xdafe"
denylister = "0xcade"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
