[package]
name = "accudo-db-tool"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-backup-cli = { workspace = true }
accudo-block-executor = { workspace = true }
accudo-config = { workspace = true }
accudo-db = { workspace = true, features = ["db-debugger"] }
accudo-db-indexer = { workspace = true }
accudo-executor = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-logger = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-temppath = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true }
accudo-vm-environment = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
accudo-backup-cli = { workspace = true, features = ["testing"] }
accudo-backup-service = { workspace = true }
accudo-executor-test-helpers = { workspace = true }
accudo-indexer-grpc-table-info = { workspace = true }
