[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework/", rev = "main" }

[addresses]


