[package]
name = "ConfidentialAssetExample"
version = "1.0.0"

[dependencies]
AccudoFramework = { local = "../../framework/accudo-framework" }
AccudoExperimental = { local = "../../framework/accudo-experimental" }

[addresses]
confidential_asset_example = "_"
