[package]
name = "ApiTest"
version = "0.0.0"

[addresses]
# test user address to be installed dynamically on build

[dependencies]
AccudoFramework = { local = "../../accudo-move/framework/accudo-framework" }
