[package]
name = "accudo-netcore"
description = "Accudo netcore"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-memsocket = { workspace = true }
accudo-proxy = { workspace = true }
accudo-types = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
accudo-memsocket = { workspace = true }
accudo-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["accudo-memsocket/fuzzing", "accudo-types/fuzzing"]
testing = ["accudo-memsocket/testing"]
