[package]
name = 'guild'
version = '1.0.0'

[addresses]
guild = "_"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
AccudoTokenObjects = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-token-objects", rev = "mainnet" }
