[package]
name = "accudo-jwk-consensus"
description = "Accudo JWK consensus"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-bitvec = { workspace = true }
accudo-bounded-executor = { workspace = true }
accudo-channels = { workspace = true }
accudo-config = { workspace = true }
accudo-consensus-types = { workspace = true }
accudo-crypto = { workspace = true }
accudo-enum-conversion-derive = { workspace = true }
accudo-event-notifications = { workspace = true }
accudo-infallible = { workspace = true }
accudo-jwk-utils = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-network = { workspace = true }
accudo-reliable-broadcast = { workspace = true }
accudo-runtimes = { workspace = true }
accudo-safety-rules = { workspace = true }
accudo-time-service = { workspace = true }
accudo-types = { workspace = true }
accudo-validator-transaction-pool = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-channel = { workspace = true }
futures-util = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }

[dev-dependencies]
accudo-types = { workspace = true, features = ["fuzzing"] }
accudo-validator-transaction-pool = { workspace = true, features = ["fuzzing"] }
[features]
smoke-test = []
