[package]
name = "accudo"
description = "Accudo tool for management of nodes and interacting with the blockchain"
version = "7.10.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-api-types = { workspace = true }
accudo-backup-cli = { workspace = true }
accudo-bitvec = { workspace = true }
accudo-build-info = { workspace = true }
accudo-cached-packages = { workspace = true }
accudo-cli-common = { workspace = true }
accudo-config = { workspace = true }
accudo-crypto = { workspace = true }
accudo-faucet-core = { workspace = true }
accudo-framework = { workspace = true }
accudo-gas-profiling = { workspace = true }
accudo-gas-schedule = { workspace = true }
accudo-genesis = { workspace = true }
accudo-github-client = { workspace = true }
accudo-global-constants = { workspace = true }
accudo-indexer-grpc-server-framework = { workspace = true }
accudo-indexer-processor-sdk = { workspace = true }
accudo-keygen = { workspace = true }
accudo-ledger = { workspace = true }
accudo-localnet = { workspace = true }
accudo-logger = { workspace = true }
accudo-move-debugger = { workspace = true }
accudo-network-checker = { workspace = true }
accudo-node = { workspace = true }
accudo-rest-client = { workspace = true }
accudo-sdk = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-telemetry = { workspace = true }
accudo-temppath = { workspace = true }
accudo-transaction-simulation = { workspace = true }
accudo-transaction-simulation-session = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true, features = ["testing"] }
accudo-vm-environment = { workspace = true }
accudo-vm-genesis = { workspace = true }
accudo-vm-logging = { workspace = true }
accudo-vm-types = { workspace = true }
accudo-workspace-server = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
bollard = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env", "unstable-styles", "wrap_help"] }
clap_complete = { workspace = true }
colored = { workspace = true }
dashmap = { workspace = true }
diesel = { workspace = true, features = ["postgres_backend"] }
diesel-async = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
legacy-move-compiler = { workspace = true }
maplit = { workspace = true }
move-asm = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-source-map = { workspace = true }
move-cli = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler-v2 = { workspace = true }
move-core-types = { workspace = true }
move-coverage = { workspace = true }
move-decompiler = { workspace = true }
move-disassembler = { workspace = true }
move-ir-types = { workspace = true }
move-linter = { workspace = true }
move-model = { workspace = true }
move-package = { workspace = true }
move-prover-boogie-backend = { workspace = true }
move-symbol-pool = { workspace = true }
move-unit-test = { workspace = true, features = ["debugging"] }
move-vm-runtime = { workspace = true, features = ["testing"] }
open = { workspace = true }
pathsearch = { workspace = true }
poem = { workspace = true }
processor = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
self_update = { git = "https://github.com/banool/self_update.git", rev = "8306158ad0fd5b9d4766a3c6bf967e7ef0ea5c4b", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
set_env = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[features]
default = []
fuzzing = []
no-upload-proposal = []
indexer = ["accudo-node/indexer"]
cli-framework-test-move = []

[build-dependencies]
shadow-rs = { workspace = true }
