apiVersion: v1
kind: Service
metadata:
  name: {{ include "accudo-fullnode.fullname" . }}-lb
  labels:
    {{- include "accudo-fullnode.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "accudo-fullnode.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: fullnode
  ports:
  {{- if .Values.service.exposeApi }}
  - name: api
    port: 80
    targetPort: 8080
  {{- end }}
  {{- if .Values.service.exposeMetrics }}
  - name: metrics
    port: 9101
    targetPort: 9101
  {{- end }}
  {{- if .Values.service.exposeAdmin }}
  - name: admin
    port: 9102
    targetPort: 9102
  {{- end }}
  - name: accudonet
    port: 6182
  {{- with .Values.service }}
  type: {{ .type }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  loadBalancerSourceRanges:
    {{- toYaml .loadBalancerSourceRanges | nindent 4 }}
  {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "accudo-fullnode.fullname" . }}
  labels:
    {{- include "accudo-fullnode.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "accudo-fullnode.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: fullnode
  ports:
  - name: backup
    port: 6186
  - name: metrics
    port: 9101
