[package]
name = "AccudoFramework"
version = "1.0.0"

[addresses]
std = "0x1"
accudo_std = "0x1"
accudo_framework = "0x1"
accudo_fungible_asset = "0xA"
accudo_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"

[dependencies]
AccudoStdlib = { local = "../accudo-stdlib" }
MoveStdlib = { local = "../move-stdlib" }
