[package]
name = "accudo-reliable-broadcast"
description = "Accudo Reliable Broadcast Implementation"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-bounded-executor = { workspace = true }
accudo-consensus-types = { workspace = true }
accudo-enum-conversion-derive = { workspace = true }
accudo-infallible = { workspace = true }
accudo-logger = { workspace = true }
accudo-time-service = { workspace = true }
accudo-types = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
futures = { workspace = true }
futures-channel = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }

[dev-dependencies]
accudo-consensus-types = { workspace = true, features = ["fuzzing"] }
accudo-time-service = { workspace = true, features = ["testing"] }

[features]
default = []
