[package]
name = "AA"
version = "0.0.0"

[addresses]
aa = "_"

[dependencies]
AccudoFramework = { local = "../../../framework/accudo-framework" }
AccudoStdlib = { local = "../../../framework/accudo-stdlib" }
