[package]
name = "TooLargeTest"
version = "0.0.0"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "move-stdlib", rev = "mainnet" }
