[package]
name = "accudo-ledger"
description = "Library for integration with the Accudo app on Ledger"
version = "0.2.0"
publish = true

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = "https://github.com/accudo-labs/accudo-core/tree/main/crates/accudo-ledger"
rust-version = { workspace = true }

[dependencies]
accudo-crypto = { workspace = true }
accudo-types = { workspace = true }
hex = { workspace = true }
ledger-apdu = "0.10.0"
ledger-transport-hid = "0.10.0"
thiserror = { workspace = true }
