[package]
name = "accudo-transaction-filters"
description = "The transaction filters used by various Accudo components."
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-crypto = { workspace = true }
accudo-types = { workspace = true }
move-core-types = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
accudo-crypto = { workspace = true, features = ["fuzzing", "testing"] }

[features]
fuzzing = []
