[package]
name = "accudo-event-notifications"
description = "The notification service offered by state sync for on-chain events"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-channels = { workspace = true }
accudo-id-generator = { workspace = true }
accudo-infallible = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-types = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
accudo-crypto = { workspace = true }
accudo-db = { workspace = true }
accudo-executor-test-helpers = { workspace = true }
accudo-temppath = { workspace = true }
accudo-vm = { workspace = true }
accudo-vm-genesis = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
