[package]
name = "accudo-schemadb"
description = "Accudo schemadb"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-drop-helper = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-storage-interface = { workspace = true }
dunce = { workspace = true }
proptest = { workspace = true, optional = true }
rand = { workspace = true }
rocksdb = { workspace = true }

[dev-dependencies]
accudo-temppath = { workspace = true }
byteorder = { workspace = true }
proptest = { workspace = true }

[features]
fuzzing = ["proptest"]
