[package]
name = "accudo-network-checker"
description = "Accudo network checker"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-config = { workspace = true }
accudo-crypto = { workspace = true }
accudo-logger = { workspace = true }
accudo-network = { workspace = true }
accudo-types = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

