[package]
name = "Pyth"
version = "0.0.1"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }

[addresses]
pyth = "_"
