[package]
name = "calculator"
version = "0.0.0"

[addresses]
account = "_"

[dependencies]
AccudoFramework = { local = "../../../framework/accudo-framework" }
AccudoStdlib = { local = "../../../framework/accudo-stdlib" }
