[package]
name = "accudo-backup-cli"
description = "Backup CLI"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-backup-service = { workspace = true }
accudo-config = { workspace = true }
accudo-crypto = { workspace = true }
accudo-db = { workspace = true }
accudo-db-indexer-schemas = { workspace = true }
accudo-executor = { workspace = true }
accudo-executor-test-helpers = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-indexer-grpc-table-info = { workspace = true }
accudo-infallible = { workspace = true }
accudo-jellyfish-merkle = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-proptest-helpers = { workspace = true }
accudo-push-metrics = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-temppath = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true }
accudo-vm-environment = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-io-timeout = { workspace = true }
tokio-stream = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }

[dev-dependencies]
accudo-backup-service = { workspace = true }
accudo-config = { workspace = true }
accudo-db = { workspace = true }
accudo-executor-test-helpers = { workspace = true }
accudo-proptest-helpers = { workspace = true }
accudo-storage-interface = { workspace = true }
proptest = { workspace = true }
warp = { workspace = true }

[features]
testing = []
fuzzing = ["accudo-db/fuzzing"]
