[package]
name = "accudo-indexer-grpc-cache-worker"
description = "Indexer gRPC worker to collect on-chain data from node gRPC and push to cache."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-indexer-grpc-server-framework = { workspace = true }
accudo-indexer-grpc-utils = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-moving-average = { workspace = true }
accudo-protos = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
futures-core = { workspace = true }
once_cell = { workspace = true }
prost = { workspace = true }
redis = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
accudo-config = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }

[features]
integration-tests = []
