[package]
name = "accudo-executor"
description = "Accudo executor"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-block-executor = { workspace = true }
accudo-consensus-types = { workspace = true }
accudo-crypto = { workspace = true }
accudo-drop-helper = { workspace = true }
accudo-executor-service = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-experimental-runtimes = { workspace = true }
accudo-infallible = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
fail = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
accudo-cached-packages = { workspace = true }
accudo-config = { workspace = true }
accudo-db = { workspace = true }
accudo-db-indexer = { workspace = true, features = ["fuzzing"] }
accudo-executor-test-helpers = { workspace = true }
accudo-indexer-grpc-table-info = { workspace = true }
accudo-sdk = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-temppath = { workspace = true }
accudo-transaction-simulation = { workspace = true }
accudo-types = { workspace = true, features = ["testing"] }
accudo-vm-genesis = { workspace = true }
arr_macro = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["accudo-consensus-types/fuzzing", "accudo-crypto/fuzzing", "accudo-types/fuzzing", "accudo-storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "accudo-vm/failpoints"]
consensus-only-perf-test = []

[[bench]]
name = "data_collection"
harness = false
