[package]
name = "aggregator_examples"
version = "0.0.0"

[addresses]
aggregator_examples = "0xCAFE"

[dependencies]
AccudoStdlib = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-stdlib", rev = "mainnet" }
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
