[package]
name = "Event-example"
version = "0.0.1"

[addresses]
std = "0x1"
accudo_framework = "0x1"
event = "_"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
