# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.AccudoFramework]
git = "https://github.com/accudo-labs/accudo-framework.git"
subdir = "accudo-framework"
rev = "mainnet"