[package]
name = "ResourceGroupsSecondary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"
resource_groups_secondary = "_"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
ResourceGroupsPrimary = { local = "../primary" }
