[package]
name = "accudo-telemetry"
description = "Accudo utilities to collect observability data from a node and send it to a remote destination"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo-api = { workspace = true }
accudo-config = { workspace = true }
accudo-consensus = { workspace = true }
accudo-crypto = { workspace = true }
accudo-db = { workspace = true }
accudo-infallible = { workspace = true }
accudo-logger = { workspace = true }
accudo-mempool = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-network = { workspace = true }
accudo-node-resource-metrics = { workspace = true }
accudo-runtimes = { workspace = true }
accudo-state-sync-driver = { workspace = true }
accudo-telemetry-service = { workspace = true }
accudo-types = { workspace = true }
flate2 = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
httpmock = { workspace = true }
