[package]
name = "fuzzer"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
accudo-framework = { workspace = true }
accudo-language-e2e-tests = { workspace = true }
accudo-types = { workspace = true }
arbitrary = { workspace = true, features = ["derive"] }
base64 = "0.21.7"
bcs = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csv = { workspace = true }
dearbitrary = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-transactional-test-runner = { workspace = true, features = ["fuzzing"] }
rayon = { workspace = true }
sha2 = { workspace = true }
walkdir = { workspace = true }
