[package]
name = "accudo-safety-rules"
description = "Accudo safety rules"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-config = { workspace = true }
accudo-consensus-types = { workspace = true }
accudo-crypto = { workspace = true }
accudo-global-constants = { workspace = true }
accudo-infallible = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-secure-net = { workspace = true }
accudo-secure-storage = { workspace = true }
accudo-types = { workspace = true }
accudo-vault-client = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
accudo-config = { workspace = true, features = ["fuzzing"] }
accudo-consensus-types = { workspace = true, features = ["fuzzing"] }
accudo-proptest-helpers = { workspace = true }
accudo-secure-storage = { workspace = true, features = ["testing"] }
claims = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rusty-fork = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "safety_rules"
harness = false
required-features = ["testing"]

[features]
default = []
fuzzing = ["accudo-consensus-types/fuzzing", "accudo-config/fuzzing", "proptest"]
testing = ["accudo-secure-storage/testing"]
