[package]
name = "ResourceGroupsPrimary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
