[package]
name = "accudo-experimental-layered-map"
description = "Accudo LayeredMap"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ahash = { workspace = true }
accudo-crypto = { workspace = true }
accudo-drop-helper = { workspace = true }
accudo-infallible = { workspace = true }
accudo-metrics-core = { workspace = true }
bitvec = "1.0.1"
itertools = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
accudo-schemadb = { workspace = true }
accudo-temppath = { workspace = true }
criterion = { workspace = true }
itertools = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[lib]
bench = false

[[bench]]
name = "sorting"
harness = false

[[bench]]
name = "maps"
harness = false
