[package]
name = "accudo-indexer-grpc-fullnode"
description = "Accudo Indexer GRPC runtime on fullnode."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

accudo-api = { workspace = true }
accudo-api-types = { workspace = true }
accudo-bitvec = { workspace = true }
accudo-config = { workspace = true }
accudo-indexer-grpc-utils = { workspace = true }
accudo-logger = { workspace = true }
accudo-mempool = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-moving-average = { workspace = true }
accudo-protos = { workspace = true }
accudo-runtimes = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-types = { workspace = true }

move-core-types = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

accudo-api-test-context = { workspace = true }
accudo-crypto = { workspace = true }
accudo-db = { workspace = true }
accudo-executor = { workspace = true }
accudo-executor-types = { workspace = true }
accudo-framework = { workspace = true }
accudo-genesis = { workspace = true }
accudo-global-constants = { workspace = true }
accudo-mempool = { workspace = true }
accudo-mempool-notifications = { workspace = true }
accudo-proptest-helpers = { workspace = true }
accudo-sdk = { workspace = true }
accudo-secure-storage = { workspace = true }
accudo-temppath = { workspace = true }
accudo-vm = { workspace = true }
accudo-vm-validator = { workspace = true }
