[package]
name = "accudo-executor-service"
description = "Accudo executor service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
accudo-block-executor = { workspace = true }
accudo-block-partitioner = { workspace = true }
accudo-config = { workspace = true }
accudo-infallible = { workspace = true }
accudo-keygen = { workspace = true }
accudo-logger = { workspace = true }
accudo-metrics-core = { workspace = true }
accudo-node-resource-metrics = { workspace = true }
accudo-push-metrics =  { workspace = true }
accudo-secure-net = { workspace = true }
accudo-storage-interface = { workspace = true }
accudo-types = { workspace = true }
accudo-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = "3.4.0"
dashmap = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
accudo-language-e2e-tests = { workspace = true }
accudo-transaction-simulation = { workspace = true }
accudo-vm = { workspace = true }
