[package]
name = "accudo-rosetta-cli"
description = "Accudo Rosetta CLI for testing"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
accudo = { workspace = true }
accudo-logger = { workspace = true }
accudo-rosetta = { workspace = true }
accudo-types = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

