[package]
name = 'ambassador_token'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
AccudoFramework = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-framework", rev = "mainnet" }
AccudoTokenObjects = { git = "https://github.com/accudo-labs/accudo-framework.git", subdir = "accudo-token-objects", rev = "mainnet" }
