name: "Release accudo-node"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: "The release tag to create. E.g. `accudo-node-v0.2.3`:"
      branch:
        type: string
        required: true
        description: "The branch to cut the release from"
      release_title:
        type: string
        required: false
        description: 'Name of the release, e.g. "Accudo Node Release v1.2.3":'

jobs:
  release-accudo-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-python@v4

      - name: Bump accudo-node version
        uses: accudo-labs/accudo-core/.github/actions/release-accudo-node@main
        with:
          release_tag: ${{ inputs.release_tag }}
          accudo_node_cargo_toml: accudo-node/Cargo.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # pin@v6.0.1
        with:
          add-paths: accudo-node
          title: "[accudo-node] update release version"
          body: Automated release bump for ${{ inputs.release_tag }}. Change the PR base accordingly
          commit-message: "[accudo-node] update release version"
          branch: auto-release-${{ inputs.release_tag }}
          delete-branch: true
